[package]
name = "bbb-cli"
version = "1.0.1"
authors = ["clarkenciel <clarkenciel@gmail.com>"]

[dependencies]
bbb_core = { git = "https://github.com/clarkenciel/bbb-core", tag = "1.0.1" }
clap = "2.27.1"
nom = "^3.2"
rustyline = "1.0.0"
